import {
  app,
  BrowserWindow,
} from 'electron';

import {
  init as initMainToRenderer,
  sendToRenderer,
} from '../inter-process-communication/main-to-renderer';
import log from '../log';
import {
  ACTIVATE,
  BEFORE_QUIT,
  CLOSE,
  MAIN_WINDOW_ID,
  PLATFORM,
  READY,
  WINDOW_ALL_CLOSED,
} from '../universal/constants';

import { subscribeToAgentEventsFromRenderer } from './agent-handlers';
import { subscribeToFindOnPageEvents } from './find-on-page';
import './keybindings';
import { createLoadmillWebView } from './loadmill-web-app-browserview';
import './menu';
import { setOpenLinksInBrowser } from './open-links';
import { initProxyServer } from './proxy';
import { createProxyView } from './proxy-view';
import { subscribeToToggleMaximizeWindow } from './screen-size';
import { initStore } from './store';
import { subscribeToSwitchView } from './switch-views';
import { initUpdater } from './update-electron-app';

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
let mainWindow: BrowserWindow;
let forceQuit = false;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const onReady = () => {
  initStore();
  initProxyServer();
  subscribeToAgentEventsFromRenderer();
  createWindow();
};

const createWindow = () => {
  log.info('creating window');
  mainWindow = new BrowserWindow({
    show: false,
    titleBarStyle: 'hiddenInset',
    trafficLightPosition: { x: 14, y: 15 },
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });
  initUpdater(unsubscribeToCloseEvent);
  subscribeToCloseEvent(mainWindow);
  mainWindow.maximize();
  initMainToRenderer(mainWindow);
  sendToRenderer({
    data: { mainWindowId: mainWindow.webContents.id },
    type: MAIN_WINDOW_ID,
  });
  setOpenLinksInBrowser(mainWindow.webContents);
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  subscribeToToggleMaximizeWindow(mainWindow);
  const loadmillWebView = createLoadmillWebView(mainWindow);
  subscribeToFindOnPageEvents(loadmillWebView.webContents);
  const proxyView = createProxyView(mainWindow);
  subscribeToSwitchView(mainWindow, loadmillWebView, proxyView);
};

app.on(BEFORE_QUIT, () => {
  forceQuit = true;
});

app.on(READY, onReady);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on(WINDOW_ALL_CLOSED, () => {
  if (process.platform !== PLATFORM.DARWIN) {
    app.quit();
  }
});

app.on(ACTIVATE, () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  } else if (mainWindow) {
    mainWindow.show();
  }
});

const unsubscribeToCloseEvent = () => {
  mainWindow.removeListener(CLOSE, () => {});
};

const subscribeToCloseEvent = (window: BrowserWindow = mainWindow) => {
  if (window) {
    window.on(CLOSE, (event: Electron.Event) => {
      if (!forceQuit && process.platform === PLATFORM.DARWIN) {
        if (!forceQuit) {
          event.preventDefault();
          window.hide();
        }
      }
    });
  }
};
