import log from '../log';
import { Token } from '../types/token';

import { callLoadmillApi } from './call-loadmill-api';
import { get, set } from './persistence-store';
import { TOKEN } from './persistence-store/constants';
import { getUser } from './user';

export const isValidToken = (token: unknown): token is Token => (
  typeof token === 'object' &&
  token !== null &&
  'id' in token &&
  'owner' in token &&
  'token' in token
);

export const isCorrectUser = async (userId: string): Promise<boolean> => {
  const { id } = await getUser();
  return id === userId;
};

export const createAndSaveToken = async (): Promise<Token | undefined> => {
  try {
    return await _createAndSaveToken();
  } catch (e) {
    log.error('Failed to create and save token', e);
  }
};

const _createAndSaveToken = async (): Promise<Token> => {
  const response = await callLoadmillApi('settings/tokens', {
    body: JSON.stringify({
      description: 'Autogenerated by Loadmill Desktop App',
    }),
    headers: {
      'Content-Type': 'application/json',
    },
    method: 'POST',
  });

  const token = await response.json() as Token;
  log.info('Setting new token', {
    id: token.id,
    owner: token.owner,
    token: _hideToken(token.token),
  });
  set(TOKEN, token);
  return token;
};

const _hideToken = (token: string) => '*'.repeat(token.length - 4) + token.substring(token.length - 4);

export const getOrCreateToken = async (): Promise<Token | undefined> => {
  const token = get<Token>(TOKEN);
  if (isValidToken(token) && await isCorrectUser(token.owner)) {
    return token;
  }

  log.info('Token does not exists / old format / of a different user');
  log.info('Fetching new token from loadmill server');
  return await createAndSaveToken();
};
