import {
  AGENT_UI_STATUS_CONNECTED,
  AGENT_UI_STATUS_CONNECTING,
  AGENT_UI_STATUS_DISCONNECTED,
  AGENT_UI_STATUS_DISCONNECTING,
  AGENT_UI_STATUS_ERROR,
  AGENT_UI_STATUS_OUTDATED,
  AGENT_UI_STATUS_RESTARTING,
} from '../universal/constants';

export type AgentUiStatus =
  | typeof AGENT_UI_STATUS_DISCONNECTED
  | typeof AGENT_UI_STATUS_CONNECTING
  | typeof AGENT_UI_STATUS_CONNECTED
  | typeof AGENT_UI_STATUS_DISCONNECTING
  | typeof AGENT_UI_STATUS_RESTARTING
  | typeof AGENT_UI_STATUS_OUTDATED
  | typeof AGENT_UI_STATUS_ERROR;
